#!/bin/bash

# TODO: Add usage

USER=$1
NUM=$2

BASE="hammer"
DOMAIN="rcc.psu.edu"

if [ ! -n "${NUM}" ]; then
	NODE=${BASE}.${DOMAIN}
elif [ "${NUM,,}" = "all" ]; then
	for NUM in {1..12}
	do
		NODE="${BASE}${NUM}.${DOMAIN}"
	    setsid ssh -t ${USER}@${NODE} "echo \"\";echo \"\";echo \"SUCCESSFULLY CONNECTED TO HOST '\$HOSTNAME'\";echo \"\";echo \"\""
	done
	exit 0
elif [ "${NUM}" -ge 1 -a "${NUM}" -le 12 ]; then
		NODE="${BASE}${NUM}.${DOMAIN}"
else
	echo "INVALID NODE NUMBER SPECIFIED."
	exit -1
fi

setsid ssh -Y -C ${USER}@${NODE}
