#!/bin/bash
# Find out which servers you're logged onto
#
# Server names come from ~/.ssh/config file
#
# TODO: parallelize the server queries!
#
# Author: J.L. Lanfranchi
# Date:   2016-02-18

HEADER=`ps -o pid,ppid,%cpu,cputime,%mem,rss,vsz,etime,cmd | head -1`
REMOTE_COMMAND='ps -e -ww -o user:7,pid,ppid,%cpu,cputime,%mem,rss,vsz,etime,cmd | grep -e "^${USER}" | grep -v "ps -e" | grep -v sshd | grep -v "/bin/bash" | grep -v "sed " | grep -v "bash" | grep -v grep | sed -r "s/^.{8}//g" | sed -e "s/^[[:space:]]*//" -e "s/[[:space:]]*$//"'
SERVERS=`cat ~/.ssh/config | grep -E '^Host' | sed 's/^Host //' | head -10`

declare -a OUTPUT
declare -a HOST_ALIASES

COUNT=0
HA_MAXLEN=0
printf "Checking hosts: "
for HOST_ALIAS in $SERVERS
do
	printf "%s " "$HOST_ALIAS"
	HOST_ALIASES[$COUNT]="$HOST_ALIAS"
	HA_LEN=`echo "$HOST_ALIAS" | wc -m`
	(($HA_LEN > $HA_MAXLEN)) && HA_MAXLEN=$HA_LEN
	OUTPUT[$COUNT]=`ssh -q -o "BatchMode yes" -o "ConnectTimeout 5" "$HOST_ALIAS" "$REMOTE_COMMAND"`
	COUNT=$(( COUNT+1 ))
done
printf "...\n"

(($COUNT == 0)) && exit

for i in $(seq 1 $COUNT)
do
	[ -z "${OUTPUT[i]}" ] && continue
	printf "\n"
	printf "=== %s ===\n" "${HOST_ALIASES[i]}"
	echo "${HEADER}"
	echo "${OUTPUT[i]}"
done
